### ISSUE TITLE
respect const return type of GDALGetMetadata (build with GDAL 3.13+)

### ISSUE THREAD

**Issue by mdsumner** [firelab/gdalraster#866]
GDAL changed the prototype of GDALGetMetadata to return a const-qualified list (CSLConstList / const char * const *). When compiling gdalraster against newer GDAL (CI used GDAL 3.13.0dev) this leads to compilation errors like:

> invalid conversion from 'CSLConstList' {aka 'const char* const*'} to 'char**' [-fpermissive]

As an exercise for myself I tried changing the instances with version guards and it seems to work with blocks like

```c++
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 13, 0) 
        CSLConstList papszMD = GDALGetMetadata(hDriver, nullptr);
#else
        char **papszMD = GDALGetMetadata(hDriver, nullptr);
#endif
```

If that's of use I parked my mods here: https://github.com/mdsumner/gdalraster/tree/const-changes-3.13 - not entirely comfy with stylistic choices or the full context so I've only tried this out. 

There's "papszMD" and "papszMetadata" instances and also cases where declaration is done upfront or inline, so stylistically we could choose one or the other? I can PR that up if you have a preference?

**Comment by ctoney** [comment]
@mdsumner, thanks I noticed that change in the documentation but I haven't compiled against it yet. Per Evan's comment, the migration guide doesn't note that as affecting the C API (https://gdal.org/en/latest/user/migration_guide.html), and latest doc says it should be seen as ` char**` from C (https://gdal.org/en/latest/api/cpl.html#_CPPv412CSLConstList). So that's weird, I'll get a new 3.13dev and try building against it shortly...

**Comment by mdsumner** [comment]
> > As an exercise for myself I tried changing the instances with version guards and it seems to work with blocks like
> > #if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 13, 0)
> > CSLConstList papszMD = GDALGetMetadata(hDriver, nullptr);
> > #else
> > char **papszMD = GDALGetMetadata(hDriver, nullptr);
> > #endif
> 
> ```
> CSLConstList papszMD = GDALGetMetadata(hDriver, nullptr);
> ```
> 
> should work fine for any GDAL version. I just did that in QGIS: [qgis/QGIS#64557](https://github.com/qgis/QGIS/pull/64557)

Thanks @rouault !

**Comment by ctoney** [comment]
@mdsumner, could we re-enable `docker-r-gdalraster.yml`?

>This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

I see it was a little more than 60 days since I last pulled it. Is that the trigger for activity? Apologies, I guess between the holidays and working with RTools I wasn't using it for a little while, but I should be pulling it more regularly again now. The last time it built was six days ago, but the CSLConstList change was three days ago.

Thanks!

**Comment by mdsumner** [comment]
Ah, should be good again: https://github.com/mdsumner/gdal-builds/pkgs/container/gdal-builds

I think it got retired after a no-change duration, an email I didn't act on 🙏

**Comment by ctoney** [comment]
Awesome, thank you.

Fixed in #868

It should work with any GDAL version so I made the changes without the conditionals. It also passed the sanitizer and valgrind checks in my fork (https://github.com/ctoney/gdalraster/actions/runs/21090325038).
